### ISSUE TITLE
Undefined plantUML path in adoc file in slides

### ISSUE THREAD

**Issue by Bullfrog666** [Riduidel/aadarchi#102]
The adoc files in architecture-documentation/src/slides/asciidoc tries to get some plantUML but it consider the atribute in the pah as undefined (like in issue #99).

The lines :
`[plantuml, {plantumldir}agile.architecture.containers, svg, opts="interactive", style="max-width:90%"]`
`include::{structurizrdir}/agile.architecture.containers.plantuml[]`

return this error in the adoc generation :
`Failed to generate image: PlantUML preprocessing failed: [From <input> (line 2) ]
@startuml
Unresolved directive in can_c4_see_forward.adoc - include::{structurizrdir}/agile.architecture.containers.plantuml[]
^^^^^
 Syntax Error?
Unresolved directive in can_c4_see_forward.adoc - include::{structurizrdir}/agile.architecture.containers.plantuml[]`

The problem seems to come from "{plantumldir}" and "{structurizrdir}" concidered as undefined, even if initialized in the pom.xml.

**Comment by Riduidel** [comment]
Interesting ... in lines 588/589 of `architecture-documentation/pom.xml` we have

```
										<plantumldir>images/</plantumldir>
										<structurizrdir>${agile.architecture.output.diagrams}</structurizrdir>
```

Moreover, it works well on my machine. We'll take a look at that on monday.
