### ISSUE TITLE
Use target `workspace.dsl`

### ISSUE THREAD

**Issue by Bullfrog666** [Riduidel/aadarchi#197]
At the moment, we use the `workspace.dsl` provided in `src/architecture/resources/worspace.dsl`

So if the user didn't provide a `workspace.dsl`, the build fail.
And that, even if user ask to generate a `workspace.dsl` (`toDslEnabled = true`), because the workspace is then generated in `target/structurizr/workspace.dsl`

We should use the one in target to avoid the problems.

And if `toDslEnabled` is false, copy the `workspace.dsl` provided in `src/architecture/resources/worspace.dsl` in target (if it doesn't exist, error).

**Comment by Riduidel** [comment]
nope, this is of no use
