### ISSUE TITLE
Automaticaly update the readme when there is a new release

### ISSUE THREAD

**Issue by Bullfrog666** [Riduidel/aadarchi#270]
Use github actions to update the readme file when a new release is done

**Comment by Riduidel** [comment]
We can potentially use

* https://github.com/marketplace/actions/readme-replacer-readme-workflows
* https://github.com/marketplace/actions/find-and-replace
* https://github.com/unfor19/replacer-action/blob/master/README.md
*

**Comment by Riduidel** [comment]
TO me, it seems like the simplest way is to use the find and repalce action
