### ISSUE TITLE
Update archetype and add the file architecture/ressources

### ISSUE THREAD

**Issue by Bullfrog666** [Riduidel/aadarchi#271]
For the moment, when you generate the Archetype (with `mvn archetype:generate` comand), there is no `architecture/ressources` file created.
Update the archetype to add this directory.

**Comment by Sese-collab** [comment]
The aim is to change  the `mvn archetype:generate` comand to create the file `archetype-metadata.xml` in `architecture/ressources` ?

**Comment by Riduidel** [comment]
No, it's the contrary.

The archetype maven module contains in `src/main/resources/archetype-resources/` (the folder which is deployed on user machine when archetype is installed) an `src` folder in which you should create the `architecture/resources/workspace.dsl` file in which we would put the default value found on [structurizr-dsl home page](https://structurizr.com/dsl).

Is it clear enough?

**Comment by Sese-collab** [comment]
Yes it's clear
