### ISSUE TITLE
Update views after enhancements

### ISSUE THREAD

**Issue by Riduidel** [Riduidel/aadarchi#274]
Currently, views are created at workspace.dsl loading. This prevents enhancements (typically maven ones).

Hopefully, the enhancer already exists : it is `ViewUpdater`, located into architecture-documentation.

So

1. Move `ViewUpdater` into `base` project `org.ndx.aadarchi.base.enhancers.graph` package
2. In `ViewUpdater`, remove the name based check and only apply view updating on filtered view (https://github.com/structurizr/dsl/blob/master/docs/language-reference.md#filtered-view)
3. Add in documentation (but where?) the fact that view updating will be based on filtered view

**Comment by Sese-collab** [comment]
do I have to include or exclude some elements for the filtered view?

**Comment by Riduidel** [comment]
No, you take all elements added during discovery to current diagram. That's exactly what ViewUpdater do. However, if you have any idea on how to have some views updated while others are not it could be very cool.

**Comment by Riduidel** [comment]
So, steps are

- [ ] Move `ViewUpdater` in base module
- [ ] Remove the various `if` in ViewUpdater
- [ ] Update the `ViewEnhancerAdapter` to add the handling of `FilteredView`
- [ ] Rework the `ViewUpdater to process only `FilteredView`
- [ ] Visit them with a secondary visitor that will perform enhancement

**Comment by Riduidel** [comment]
Seems like updating structurizr to latest version would allow definition of properties in views (see https://github.com/structurizr/java/releases/tag/v1.16.1) which in turn would allow us to reuse the initial view updated with an `aadarchi.auto.include` property set to true` (or any non-false value).

@Sese-collab Can you take a look at that possibility ?
