### ISSUE TITLE
Create a model linting module

### ISSUE THREAD

**Issue by Riduidel** [Riduidel/aadarchi#312]
This simple enhancer would check for each element some useful things

* An element must have a description set
* A container/component must have a technology set
* A relationship must have a description set
* A relationship should have a technology set (as well as an interaction style)

We should see with Simon Brown what would be interesting, and we should get more ideas from https://c4model.com/bingo/

**Comment by Sese-collab** [comment]
An element and relationship have a technology string or a description. I don't understand the point of set. 
Also, should I return a logger.error when they are missing?

**Comment by Riduidel** [comment]
When things are ok, there is no need to log anything

**Comment by Riduidel** [comment]
See also https://github.com/neuland/assertj-logging (which would need a java.util.logging implementation)

**Comment by Riduidel** [comment]
This Stackoverflow answer may help https://stackoverflow.com/a/1834789/15619
