### ISSUE TITLE
Why do I have to specify the version twice ?

### ISSUE THREAD

**Issue by lhauspie** [Riduidel/aadarchi#318]
The command to generate the project with the maven archetype is :
```
$ mvn archetype:generate -DarchetypeVersion=0.1.6 -Daadarchi-version=0.1.6 -DarchetypeGroupId=io.github.Riduidel.aadarchi -DarchetypeArtifactId=archetype 
```

As far as I know, the archetype and other modules (like base) have exactly the same maven lifecycle.

So if you release a new version of `aadarchi`, the archetype version will be increased at the same time than `base` module for example.

So why do I have to specify the version of aadarchi dependencies ?
It could be inferred from `-DarchetypeVersion=0.1.6` param and if I want to specify another version I could overwrite it with the `-Daadarchi-version=0.1.6` param (even if I suppose there might have breaking change between two version).

**Comment by Riduidel** [comment]
Fixed in #313 : archetype version is the aadarchi version without any cumbersome parameter passing
