### ISSUE TITLE
Decisions PDFs should be in `decisions` directory

### ISSUE THREAD

**Issue by lhauspie** [Riduidel/aadarchi#321]
After running `mvn clean install`there is PDFs that represents decisions at the root folder.
Maybe they should be inside the `decisions` directory ?

<img width="235" alt="image" src="https://user-images.githubusercontent.com/25682509/220167048-b909baf8-576c-4ff4-95f0-85711b510404.png">

**Comment by Riduidel** [comment]
In fact, it would be better to have no adr file visible by changing the `001_use_adr.adoc` file into `_001_use_adr.adoc`
