### ISSUE TITLE
out-of-the-box diagrams are not in docs

### ISSUE THREAD

**Issue by lhauspie** [Riduidel/aadarchi#328]
```shell
mvn archetype:generate -DarchetypeVersion=0.1.10 -DarchetypeGroupId=io.github.Riduidel.aadarchi -DarchetypeArtifactId=archetype
```

then
```shell
mvn clean package
```

But PDF or HTML do not contain diagrams:
<img width="1128" alt="image" src="https://user-images.githubusercontent.com/25682509/223785181-1cbb0475-c19d-43c6-9f32-78de622c6bee.png">

<img width="784" alt="image" src="https://user-images.githubusercontent.com/25682509/223785341-cbb78757-2d9d-48f5-adda-5d945cf6f34d.png">

The content of context.adoc is the default one:
```
// This is an example diagram to show how to include a structurizr-generated diagram
[plantuml, {plantumldir}SystemContext, svg, opts="inline"]
----
include::{structurizrdir}/SystemContext.plantuml[]
----
```

Maybe a problem with plantumldir or structurizrdir ?

----

For information:
```shell
mvn -v
Apache Maven 3.9.0 (9b58d2bad23a66be161c4664ef21ce219c2c8584)
Maven home: /Users/lhauspie/.asdf/installs/maven/3.9.0
Java version: 11, vendor: Oracle Corporation, runtime: /Users/lhauspie/.asdf/installs/java/openjdk-11
Default locale: fr_FR, platform encoding: UTF-8
OS name: "mac os x", version: "10.16", arch: "x86_64", family: "mac"
```

**Comment by lhauspie** [comment]
I noticed that the image is not rendered but included as a kind of very long url to kroki that take one line on several pages:
<img width="1115" alt="image" src="https://user-images.githubusercontent.com/25682509/223787391-10eaf581-79cc-4b94-8081-c403c14662cd.png">
<img width="1115" alt="image" src="https://user-images.githubusercontent.com/25682509/223787530-a2a34942-3f73-4648-955f-9d6fff5a5309.png">

**Comment by Riduidel** [comment]
What happens if you open this url in your browser ?

**Comment by lhauspie-adeo** [comment]
<img width="1211" alt="image" src="https://user-images.githubusercontent.com/52406406/224365310-1bcda2cb-d5cf-4fdd-81ef-11e74fb9bab8.png">

**Comment by lhauspie-adeo** [comment]
I just retry and this time, the first SystemContext diagram is displaying well but not the System Containers.
<img width="1211" alt="image" src="https://user-images.githubusercontent.com/52406406/224367192-4ab1c354-ac83-42a9-853e-bdce368c0353.png">

To validate an hypothesis, I disabled my WiFi and as Kroki is unreachable no diagrams was displayed.
It could be nice to fail the build in case of problem during the images generation via Kroki to avoid to release my documentation without any diagrams.

**Comment by Riduidel** [comment]
See #333 for error handling
