### ISSUE TITLE
Reintegrate readme update  into maven build

### ISSUE THREAD

**Issue by Riduidel** [Riduidel/aadarchi#331]
Using a github action for that is in fact suboptimal, so remove the `.github/workflows/on_release_update_readme.yml` action and replace it with the correct set of maven plugins

**Comment by Helielzel** [comment]
Currently looking for search and replace / file modifications maven plugins.
I'm checking resources such as 

- https://github.com/floverfelt/find-and-replace-maven-plugin
- https://code.google.com/archive/p/maven-replacer-plugin

**Comment by Helielzel** [comment]
And here : https://maven.apache.org/plugins/index.html

**Comment by Helielzel** [comment]
https://floverfelt.org/find-and-replace-maven-plugin/examples/basic.html

**Comment by Riduidel** [comment]
> * Does the plugin need to modify just a line in the README or a variable containing the version to change ?

Since the readme is a markdown file, which has no interpolation mechanism, we will have to directly change the line
> 
> * Does it need to remove the .yml or can i just do it myself

You'll have to remove the yml  file by youself
> 
> * Does it need to be in a particular place in the pom.xml file or can i just put it at the end of  after the last actual plugin ?

Have you ever heard about [maven profiles](https://maven.apache.org/guides/introduction/introduction-to-profiles.html) ? Since your coe will have to be run only during maven release process, there is a way  to trigger that by putting your code in a profile, and having that profile activated on release (see [`poml.xml`](https://github.com/Riduidel/aadarchi/blob/main/pom.xml#L446))

**Comment by Riduidel** [comment]
Command to use to test your code is `mvn package --projects :system --activate-profiles settings-aadarchi,update_version_in_files`

**Comment by Riduidel** [comment]
Then validate the `README.md` now contains the new version

**Comment by Helielzel** [comment]
The project version on the on_release_perform_maven_release.yml file is set to default, so i have a doubt about replacing the version number from the readme by this one. (so I think I just forgotten where i have to take it. Not in the on_release_update_readme.yml I assume, since I'me supposed to delete it)
But so far I've been able to modify the readme file with the find-and-replace-maven-plugin

**Comment by Helielzel** [comment]
Task finished, but only one issue remains : if the command is run multiple times, the SNAPSHOT is added multiple times too at the end of the version

**Comment by Riduidel** [comment]
Won't fix (we prefer to use the github action for that, as it generates a PR)
