### ISSUE TITLE
Change log format of aadarchi-maven-plugin

### ISSUE THREAD

**Issue by Riduidel** [Riduidel/aadarchi#340]
We currently output logs in the form

```
[[1;34mINFO[m] (org.ndx.aadarchi.base.ArchitectureEnhancer) Running enhancement org.ndx.aadarchi.base.enhancers.scm.SCMProjectCheckouter took 00:00:00.021
```

Can you

1. Replace the parenthesis around class name by square brackets
2. Limit the number of characters of this class name to 20
3. Compress package names to only have first character

This would lead to log being in the form

```
[[1;34mINFO[m] <o.n.a.base.ArchitectureEnhancer> Running enhancement org.ndx.aadarchi.base.enhancers.scm.SCMProjectCheckouter took 00:00:00.021

```

**Comment by Riduidel** [comment]
I suggest you  take a look at class `MavenLoggingRedirectorHandler`

**Comment by Helielzel** [comment]
Compile with -X to display logs ?

**Comment by Helielzel** [comment]
`    public static String shortenSource(String originalSource) {
        String[] parts = originalSource.split("\\.");
        StringBuilder newSource = new StringBuilder();
        System.out.println(parts.length);
        for (int i = 0; i < parts.length - 1; i++) {
            if (i > 0) {
                newSource.append(".");
            }
            newSource.append(parts[i].charAt(0));
        }
        newSource.append("." + parts[parts.length - 1]);
        return newSource.toString();
    }`

**Comment by Riduidel** [comment]
More clearly, if full class name (including packages) is smaller than 20 characters, show everything.
If full class name is longer than 20 characters, start by replacing package names by their first letter, starting by the first one. Never compress class name.

Here are some example

* `org.ndx.aadarchi.gitlab.GitlabSCMHandler` should be abbreviated to `o.n.a.g.GitlabSCMHandler` (24 characters)
* `org.ndx.aadarchi.base.enhancers.ToDsl` should be abbreviated to `o.n.a.b.e.ToDsl` (16 characters)

I think you could write that in a unit test ...

**Comment by Helielzel** [comment]
```
    public static Integer getTotalSize(String[] parts) {
        int totalSize = 0;

        for (int i = 0; i < parts.length - 1; i++) {
            totalSize += parts[i].length() + 1;
        }
        return totalSize;
    }

    public static String shortenSource(String originalSource) {
        if (originalSource.length() <= 20) {
            return originalSource;
        }

        String[] parts = originalSource.split("\\.");
        StringBuilder newSourceBuilder = new StringBuilder();
        int classLength = parts[parts.length - 1].length();
        /*
        if (classLength >= 20) {
            for (int i = 0; i < parts.length - 1; i++) {
                newSourceBuilder.append(parts[i].charAt(0) + ".");
            }
            return newSourceBuilder.append(parts[parts.length - 1]).toString();
        }*/
        for (int i = 0; i < parts.length - 1; i++) {
            if (getTotalSize(parts) + classLength > 20) {
                //parts[i] = parts[i].replace(parts[i], String.valueOf(parts[i].charAt(0)));
                parts[i] = String.valueOf(parts[i].charAt(0));
            }
            newSourceBuilder.append(parts[i] + ".");
        }
        return newSourceBuilder.append(parts[parts.length - 1]).toString();
    }
```

**Comment by Helielzel** [comment]
```
public static Integer getTotalSize(String[] parts) {
    return Arrays.stream(parts)
            .limit(parts.length - 1)
            .mapToInt(String::length)
            .sum() + parts.length - 1;
}

public static String shortenSource(String originalSource) {
    String[] parts = originalSource.split("\\.");
    int classLength = parts[parts.length - 1].length();

    if (getTotalSize(parts) + classLength > 20) {
        parts = Arrays.stream(parts)
                .limit(parts.length - 1)
                .map(s -> s.substring(0, 1))
                .toArray(String[]::new);
    }

    return String.join(".", parts);
}
```
