### ISSUE TITLE
.asciidoctorconfig.adoc missing in archetype

### ISSUE THREAD

**Issue by nabsha-sv** [Riduidel/aadarchi#355]
Hi Team,

Just cloned the `archetype` project to set it up locally and I noticed that asciidoc config `architecture-documentation/.asciidoctorconfig.adoc` is not defined and hence no `structurizrdir` variable.

```
Failed to generate image: PlantUML preprocessing failed: [From <input> (line 2) ]

@startuml
Unresolved directive in _Aadarchi_base.adoc - include::{structurizrdir}/diagrams/base_components.plantuml[]
^^^^^
 Syntax Error?

Unresolved directive in _Aadarchi_base.adoc - include::{structurizrdir}/diagrams/base_components.plantuml[]
```

I can see in the [base project](https://github.com/Riduidel/aadarchi) `architecture-documentation/.asciidoctorconfig.adoc` exist(but is also missing `structurizrdir` variable), but not in `archetype` output.

**Comment by Riduidel** [comment]
Hello @nabsha-sv 
In fact, you shouldn't even clone the archetype project. You really have, according to [`README.md`](https://github.com/Riduidel/aadarchi/blob/main/README.md) to run the following command. This should give you a working project.

Don't get too much worried about the `.asciidoctorconfig.adoc` file, it has been generated on y machine and I commited it by mistake

**Comment by nabsha-sv** [comment]
hmm... so I did the following
```
 7126  mvn archetype:generate -DarchetypeVersion=0.1.10 -Daadarchi-version=0.1.10 -DarchetypeGroupId=io.github.Riduidel.aadarchi -DarchetypeArtifactId=archetype
 7127  cd test-artifact
 7128  ls
 7129  mvn clean install
 7130  ....
 7131  mvn -Plivereload
```

and changed a few things in `src/docs/asciidoc/_01-context.adoc`, should I expect to change `target/structurizr/enhancements/_01-context.adoc` and/or under `target/asciidoc/docs/html`? as none of them are getting updated.

Note: My `workspace.dsl` changes are reflected correctly though, I primarily am interested in the framework and the sequence diagram generator.

**Comment by Riduidel** [comment]
Sorry for the late reply.
In fact, there should be changes to `target/asciidoc/docs/html` (that's the whole point of the live reload). Can you send the log file once `mvn -Plivereload` is invoked ? (ideally, if you could push your project to GitHub (or send me a zip file containing it), it would help
