### ISSUE TITLE
duplicate `:` in the generation script

### ISSUE THREAD

**Issue by lhauspie** [Riduidel/aadarchi#36]
When I ran this command :
```
mvn archetype:generate -DarchetypeVersion=0.0.3 -DarchetypeRepository=https://jitpack.io -DarchetypeGroupId=com.github.Riduidel.agile-architecture-documentation-system -DarchetypeArtifactId=archetype -Pjitpack
```

I see that there is two times the `:` in the following log trace :
```
Define value for property 'package' com.lhauspie.example: : 
```

**Comment by Riduidel** [comment]
Well, I guess it is more a bug of the maven-archetype-plugin as I have no control over the way it is displayed.

**Comment by Riduidel** [comment]
Is that bug still existing with latest version?

**Comment by Riduidel** [comment]
Closed by lack of activity
